"""add description to Plans

Revision ID: 823b7bda0942
Revises: b95b14522e07
Create Date: 2025-03-25 11:35:07.684278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823b7bda0942'
down_revision: Union[str, None] = 'b95b14522e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('description', sa.String(length=8191), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'description')
    # ### end Alembic commands ###
